export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const UPDATE_MODAL = 'UPDATE_MODAL'

export const GET_STUDENTS = 'GET_STUDENTS'
export const SAVE_STUDENT_DATA = 'SAVE_STUDENT_DATA'

export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_STUDENT_DATA = 'UPDATE_STUDENT_DATA'

export const ADD_STUDENT = 'ADD_STUDENT'
export const ADD_STUDENT_DATA = 'SAVE_ADD_STUDENT_DATA'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_DATA = 'DELETE_STUDENT_DATA'