version: '3'
services:
  app:
    build:
      context: .
    ports: ["8080:8080"]
    entrypoint: /app/scripts/wait-for-it.sh db:5432 -- make start-prod
    environment:
      - DATABASE_URL=postgresql://user:SuperSecurePassword@db/school
    depends_on:
      - db

  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=SuperSecurePassword
      - POSTGRES_DB=school
    volumes: 
      - the-flask-test:/var/lib/postgresql/data
    expose: [5432]
    
volumes:
    the-flask-test:
      external: false